application: arctic-pad-127914
version: 3
runtime: php55
api_version: 3
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: index.php
