application: arctic-pad-127914
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: index.php
  
- url: /thank_you\.php
  script: thank_you.php
  
- url: /q1\.html
  script: q1.html

- url: /js
  static_dir: js
